import type { Transaction, Category } from '@/lib/types';

export const categories: Category[] = [
  { value: 'food-drink', label: 'Food & Drink', icon: 'Utensils' },
  { value: 'shopping', label: 'Shopping', icon: 'ShoppingCart' },
  { value: 'transport', label: 'Transport', icon: 'Car' },
  { value: 'groceries', label: 'Groceries', icon: 'ShoppingBasket' },
  { value: 'home', label: 'Home', icon: 'Home' },
  { value: 'entertainment', label: 'Entertainment', icon: 'Ticket' },
  { value: 'health', label: 'Health', icon: 'HeartPulse' },
  { value: 'utilities', label: 'Utilities', icon: 'Lightbulb' },
  { value: 'travel', label: 'Travel', icon: 'Plane' },
  { value: 'personal-care', label: 'Personal Care', icon: 'Smile' },
];

export const transactions: Transaction[] = [
  {
    id: 'txn_1',
    date: '2024-07-15',
    description: 'STARBUCKS COFFEE',
    amount: -12.5,
    category: 'food-drink',
    status: 'reviewed',
  },
  {
    id: 'txn_2',
    date: '2024-07-15',
    description: 'AMAZON MKTPLACE PMTS',
    amount: -78.99,
    category: 'shopping',
    status: 'reviewed',
  },
  {
    id: 'txn_3',
    date: '2024-07-14',
    description: 'SHELL FUEL 1234',
    amount: -45.2,
    category: 'transport',
    status: 'pending',
  },
  {
    id: 'txn_4',
    date: '2024-07-14',
    description: 'Spotify AB',
    amount: -10.99,
    category: 'entertainment',
    status: 'reviewed',
  },
  {
    id: 'txn_5',
    date: '2024-07-13',
    description: 'WHOLE FOODS MARKET',
    amount: -120.45,
    category: 'groceries',
    status: 'reviewed',
  },
  {
    id: 'txn_6',
    date: '2024-07-13',
    description: 'UBER TRIP',
    amount: -22.1,
    category: 'transport',
    status: 'reviewed',
  },
  {
    id: 'txn_7',
    date: '2024-07-12',
    description: 'NETFLIX.COM',
    amount: -15.49,
    category: 'entertainment',
    status: 'reviewed',
  },
  {
    id: 'txn_8',
    date: '2024-07-12',
    description: 'Local Cafe Shop',
    amount: -8.0,
    category: 'food-drink',
    status: 'pending',
  },
  {
    id: 'txn_9',
    date: '2024-07-11',
    description: 'Monthly Rent Payment',
    amount: -1500.0,
    category: 'home',
    status: 'flagged',
  },
  {
    id: 'txn_10',
    date: '2024-07-10',
    description: 'ZARA CLOTHING',
    amount: -150.75,
    category: 'shopping',
    status: 'reviewed',
  },
    {
    id: 'txn_11',
    date: '2024-07-09',
    description: 'Misc hardware store',
    amount: -33.18,
    category: 'home',
    status: 'pending',
  },
    {
    id: 'txn_12',
    date: '2024-07-08',
    description: 'PAYPAL *AIRBNB',
    amount: -450.00,
    category: 'travel',
    status: 'reviewed',
  }
];
