'use client';

import * as React from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useToast } from '@/hooks/use-toast';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { CalendarIcon, PlusCircle, UploadCloud, FileText, CheckCircle, XCircle, Wand2, Loader2 } from 'lucide-react';
import { Calendar } from '@/components/ui/calendar';
import { format } from 'date-fns';
import { cn } from '@/lib/utils';
import type { Transaction, Category } from '@/lib/types';
import TransactionTable from '@/components/dashboard/transaction-table';
import { preprocessTransactions } from '@/lib/preprocessing';
import { Separator } from '@/components/ui/separator';
import { synthesizeTransactions } from '@/ai/flows/synthesize-transactions';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { useUser, useFirestore, useCollection, useMemoFirebase } from '@/firebase';
import { collection, addDoc, serverTimestamp, doc, setDoc, writeBatch } from 'firebase/firestore';

export default function DataIngestionPage() {
  const { toast } = useToast();
  const { user } = useUser();
  const firestore = useFirestore();

  // Manual entry state
  const [description, setDescription] = React.useState('');
  const [amount, setAmount] = React.useState('');
  const [date, setDate] = React.useState<Date | undefined>(new Date());

  // Data from Firestore
  const transactionsQuery = useMemoFirebase(() => {
    if (!user || !firestore) return null;
    return collection(firestore, 'users', user.uid, 'transactions');
  }, [user, firestore]);
  const { data: rawTransactions, isLoading: isLoadingTransactions } = useCollection<Transaction>(transactionsQuery);
  const allTransactions = React.useMemo(() => preprocessTransactions(rawTransactions || []), [rawTransactions]);

  const categoriesQuery = useMemoFirebase(() => {
    if (!firestore) return null;
    return collection(firestore, 'categories');
  }, [firestore]);
  const { data: categories, isLoading: isLoadingCategories } = useCollection<Category>(categoriesQuery);

  // File upload state
  const [file, setFile] = React.useState<File | null>(null);
  const [isProcessing, setIsProcessing] = React.useState(false);

  // Synthetic data state
  const [isGenerating, setIsGenerating] = React.useState(false);
  const [numToGenerate, setNumToGenerate] = React.useState("5");
  const [categoryToGenerate, setCategoryToGenerate] = React.useState<string>(categories?.[0]?.id || '');

  React.useEffect(() => {
    if (categories && !categoryToGenerate) {
      setCategoryToGenerate(categories[0]?.id);
    }
  }, [categories, categoryToGenerate]);

  const handleAddTransaction = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!description || !amount || !date || !user || !firestore) {
      toast({
        variant: 'destructive',
        title: 'Missing Information',
        description: 'Please fill out all fields and ensure you are logged in.',
      });
      return;
    }

    const newTransactionData = {
      // id is auto-generated by Firestore
      date: format(date, 'yyyy-MM-dd'),
      description,
      amount: -Math.abs(parseFloat(amount)),
      category: 'other', // Default category, AI will re-classify
      status: 'pending',
      userProfileId: user.uid,
      createdAt: serverTimestamp(),
      multiCategory: { // Add default multi-category
          banking: 'other',
          behavioral: 'other',
          personalized: 'other',
          minimalist: 'other',
      },
    };

    try {
      const collectionRef = collection(firestore, 'users', user.uid, 'transactions');
      await addDoc(collectionRef, newTransactionData);

      toast({
        title: 'Transaction Added',
        description: `${description} for ₹${amount} has been added.`,
      });

      // Reset form
      setDescription('');
      setAmount('');
      setDate(new Date());

    } catch (error) {
      console.error("Error adding transaction:", error);
      toast({
        variant: 'destructive',
        title: 'Error Adding Transaction',
        description: 'Could not save the transaction to the database.',
      });
    }
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files.length > 0) {
      setFile(e.target.files[0]);
    }
  };

  const handleFileUpload = async () => {
    if (!file || !user || !firestore) {
      toast({
        variant: 'destructive',
        title: 'Upload Failed',
        description: 'Please choose a file and ensure you are logged in.',
      });
      return;
    }

    setIsProcessing(true);
    toast({
      title: 'Processing File...',
      description: `Ingesting and validating ${file.name}.`,
    });

    // In a real app, you'd parse the CSV/JSON file here.
    // For this demo, we'll simulate the file content.
    const fileTransactions: Omit<Transaction, 'id'>[] = [
      { date: '2024-07-20', description: 'DELTA AIRLINES', amount: -672.55, category: 'travel', status: 'pending', multiCategory: { banking: 'travel', behavioral: 'luxury', personalized: 'travel', minimalist: 'wants' }, userProfileId: user.uid },
      { date: '2024-07-20', description: 'HOME DEPOT #123', amount: -88.12, category: 'home', status: 'pending', multiCategory: { banking: 'home', behavioral: 'necessity', personalized: 'home', minimalist: 'necessity' }, userProfileId: user.uid },
      { date: '2024-07-20', description: 'Vendor without amount', amount: 0, category: 'home', status: 'flagged', multiCategory: { banking: 'home', behavioral: 'other', personalized: 'other', minimalist: 'other' }, userProfileId: user.uid },
    ];
    
    const validTransactions = fileTransactions.filter(t => t.amount !== 0);
    const malformedCount = fileTransactions.length - validTransactions.length;

    try {
      const batch = writeBatch(firestore);
      const collectionRef = collection(firestore, 'users', user.uid, 'transactions');
      
      validTransactions.forEach(txData => {
        const docRef = doc(collectionRef); // Create a new doc with a unique ID
        batch.set(docRef, { ...txData, createdAt: serverTimestamp() });
      });

      await batch.commit();
      
      setIsProcessing(false);
      setFile(null);

      toast({
        title: 'Ingestion Complete',
        description: (
          <div className='flex flex-col gap-2 text-sm'>
            <div className='flex items-center gap-2'><CheckCircle className='text-green-500'/><span>{validTransactions.length} records ingested successfully.</span></div>
            {malformedCount > 0 && <div className='flex items-center gap-2'><XCircle className='text-red-500' /><span>{malformedCount} malformed records were quarantined.</span></div>}
          </div>
        )
      });
    } catch (error) {
      console.error("Error batch writing transactions: ", error);
      setIsProcessing(false);
      toast({
        variant: 'destructive',
        title: 'Upload Failed',
        description: 'Could not save the uploaded transactions.',
      });
    }
  };

  const handleGenerateSyntheticData = async () => {
    if (!categoryToGenerate || !numToGenerate || !user || !firestore) {
      toast({
        variant: 'destructive',
        title: 'Missing Fields',
        description: 'Please select a category and number of transactions to generate.',
      });
      return;
    }
    
    setIsGenerating(true);
    toast({ title: "Generating synthetic data...", description: "The AI is creating new transaction records." });

    try {
      const categoryLabel = categories?.find(c => c.id === categoryToGenerate)?.label || 'Unknown';
      const result = await synthesizeTransactions({
        count: parseInt(numToGenerate, 10),
        category: categoryLabel,
      });
      
      const batch = writeBatch(firestore);
      const collectionRef = collection(firestore, 'users', user.uid, 'transactions');

      result.transactions.forEach(tx => {
        const docRef = doc(collectionRef);
        const newTx = {
          description: tx.description,
          amount: -Math.abs(tx.amount),
          date: format(new Date(), 'yyyy-MM-dd'),
          category: categoryToGenerate,
          status: 'pending',
          userProfileId: user.uid,
          createdAt: serverTimestamp(),
          multiCategory: { // Add default multi-category
            banking: categoryToGenerate,
            behavioral: 'other',
            personalized: 'other',
            minimalist: 'other',
          },
        };
        batch.set(docRef, newTx);
      });

      await batch.commit();

      toast({
        title: "Generation Complete",
        description: `${result.transactions.length} new transactions have been added.`,
      });

    } catch (error) {
      console.error("Synthetic data generation failed:", error);
      toast({
        variant: 'destructive',
        title: 'Generation Failed',
        description: 'Could not generate synthetic transaction data.',
      });
    } finally {
      setIsGenerating(false);
    }
  };


  return (
    <div className="space-y-6">
      <div>
        <h1 className="font-headline text-3xl font-semibold tracking-tight text-foreground">
          Data Ingestion & Validation
        </h1>
        <p className="text-muted-foreground">
          Add new transactions individually, via bulk upload, or generate synthetic data.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <Card className='lg:col-span-2'>
          <CardHeader>
            <CardTitle>Manual & Bulk Data Entry</CardTitle>
          </CardHeader>
          <CardContent className='grid grid-cols-1 md:grid-cols-2 gap-6'>
              <div className='space-y-4'>
                 <h3 className="font-medium">Add a Single Transaction</h3>
                <form onSubmit={handleAddTransaction} className="space-y-4">
                  <div className="space-y-2">
                    <Label htmlFor="description">Merchant Description</Label>
                    <Input
                      id="description"
                      value={description}
                      onChange={(e) => setDescription(e.target.value)}
                      placeholder="e.g., Amazon Marketplace"
                    />
                  </div>
                  <div className="grid grid-cols-2 gap-4">
                    <div className="space-y-2">
                      <Label htmlFor="amount">Amount</Label>
                      <Input
                        id="amount"
                        type="number"
                        value={amount}
                        onChange={(e) => setAmount(e.target.value)}
                        placeholder="e.g., 42.99"
                      />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="date">Date</Label>
                      <Popover>
                        <PopoverTrigger asChild>
                          <Button
                            variant={"outline"}
                            className={cn("w-full justify-start text-left font-normal", !date && "text-muted-foreground")}
                          >
                            <CalendarIcon className="mr-2 h-4 w-4" />
                            {date ? format(date, "PPP") : <span>Pick a date</span>}
                          </Button>
                        </PopoverTrigger>
                        <PopoverContent className="w-auto p-0">
                          <Calendar mode="single" selected={date} onSelect={setDate} initialFocus />
                        </PopoverContent>
                      </Popover>
                    </div>
                  </div>
                  <div className="flex justify-end">
                    <Button type="submit">
                      <PlusCircle className="mr-2 h-4 w-4" />
                      Add Transaction
                    </Button>
                  </div>
                </form>
              </div>

             <div className='space-y-4'>
                <h3 className="font-medium">Bulk Import from File</h3>
                <div className='flex flex-col gap-4 justify-center items-center text-center p-8 border-2 border-dashed border-muted rounded-lg h-[255px]'>
                  {!file ? (
                      <>
                          <div className='p-3 bg-muted rounded-full'>
                              <UploadCloud className="h-8 w-8 text-muted-foreground" />
                          </div>
                          <p className="text-muted-foreground mb-2">Drag & drop a file or click to select</p>
                          <Button variant="outline" asChild>
                              <Label htmlFor="file-upload" className='cursor-pointer'>
                                Select File
                              </Label>
                          </Button>
                          <Input id="file-upload" type="file" className="sr-only" onChange={handleFileChange} accept=".csv,.json" />
                      </>
                  ) : (
                      <div className='flex flex-col items-center gap-3'>
                          <FileText className='h-10 w-10 text-primary'/>
                          <p className='font-medium'>{file.name}</p>
                          <p className='text-xs text-muted-foreground'>Ready for ingestion</p>
                      </div>
                  )}
                </div>
                 <Button onClick={handleFileUpload} disabled={!file || isProcessing} className="w-full">
                  {isProcessing ? 'Processing...' : 'Upload and Ingest'}
                </Button>
            </div>
          </CardContent>
        </Card>
        
        <Card>
          <CardHeader>
            <CardTitle>Synthetic Data Generation</CardTitle>
            <CardDescription>
              Use the AI to create realistic sample data to bootstrap your models.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="category-select">Category</Label>
                <Select value={categoryToGenerate} onValueChange={setCategoryToGenerate} disabled={!categories || categories.length === 0}>
                  <SelectTrigger id="category-select">
                    <SelectValue placeholder="Select a category" />
                  </SelectTrigger>
                  <SelectContent>
                    {categories?.map(cat => (
                      <SelectItem key={cat.id} value={cat.id}>{cat.label}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                 {(!categories || categories.length === 0) && <p className='text-xs text-muted-foreground'>Please add a category on the Taxonomy page first.</p>}
              </div>
               <div className="space-y-2">
                <Label htmlFor="num-to-generate">Number to Generate</Label>
                <Input
                  id="num-to-generate"
                  type="number"
                  value={numToGenerate}
                  onChange={(e) => setNumToGenerate(e.target.value)}
                  placeholder="e.g., 10"
                />
              </div>
            </div>
          </CardContent>
           <CardContent>
             <Button onClick={handleGenerateSyntheticData} disabled={isGenerating || !categories || categories.length === 0} className="w-full">
              {isGenerating ? <Loader2 className="mr-2 h-4 w-4 animate-spin"/> : <Wand2 className="mr-2 h-4 w-4" />}
              {isGenerating ? 'Generating...' : 'Generate Transactions'}
            </Button>
          </CardContent>
        </Card>
      </div>

      <Separator />
      
      <Card>
        <CardHeader>
          <CardTitle>Transaction History</CardTitle>
          <CardDescription>All ingested transactions are shown here, ready for AI processing and review.</CardDescription>
        </CardHeader>
        <CardContent className="pl-2">
          {isLoadingTransactions ? (
            <div className='flex items-center justify-center h-40'>
              <Loader2 className="h-8 w-8 animate-spin text-primary" />
            </div>
          ) : (
            <TransactionTable
              transactions={allTransactions}
              categories={categories || []}
            />
          )}
        </CardContent>
      </Card>
    </div>
  );
}
